import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UsersProvider } from "../context/UsersContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
          {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className={inter.className}>
        <UsersProvider>{children}</UsersProvider>
      </body>
    </html>
  );
}
